runtime: custom
service: default
env: flex
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 20
env_variables:
  ASPNETCORE_ENVIRONMENT: Production
  FIREBASE_CREDENTIALS: |
    {
      "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDH9baUSeGUqAxf\nu4Ri2g+Ns5d6MZBfM8Qu2Pn4j8p1BktVKXJLvEoPf90oerdiKsfnyzLHeNnC2EAa\nPaZeMjFn0WyYjPyuw0+mNq8cOAh/PYoseYX0aSslYBSOjGwNu9UMhUVxTMSJMsZD\n105DQHNn6tR7d7VAQTR+X121D22+/852SpYIdDjaYK/bfdEsVG9Zzm1aQBg+sKxo\nBKUBLB1dTTydyxcJSa72WPDdrpPlnAchCYRPljiMOdY0rbcGvsaLg5WO2L34zUXx\nod0H5a1tyvJuBmH2yR3I44rEjr+VltdoRE88WRP6/INKwYK6qhg78kjH6nOLMBLD\nc9m9gvedAgMBAAECggEAMOOnPc9oi5eg2uE2p5KoPd2cmiA3K8e03j1ntLm3ZvBg\nh9Rn4ROKygpZsNV8M9DA6q/4XOPz3htQZPoQzLQZ90exdQT3nOUc+scg/lXG4hFS\nULhvo4f5KBy7OfUkUCFOIE8PYPnDjcXvytOAC5pc/Rnh1MQ6eRjYNFOtziCVFR74\nOil8bIa96YAUH3suwmnlTox2qyh7+u2rxzFRWJKPs7kcc1+PIK0bqbikFi2ZS/iW\nhE3ApduKFkLeSkZaUKfnGkG1Y4hoHX3IWhC1kIOErVELSp47j1DOWlO05voKep+R\n0ofyEtmp13WAGUyWdn7goYTdQAxIJy/0NpdyT1lLcwKBgQD2aTJ2sPotigtR3mQ+\nH9FTkhPr+Dqh8JQWjXxBLIZngqb0adOJTlcaZtvQe/nnhyJO5DAUpfxt1dtcemcG\nrR4MasW5vDr91k3xbq5Us0S2KrZai7vCAu5tD5YtxqvpmNdKEROd0gS9qe5Qdc59\nWdq/6u8/RhACN0CxpXpFwQnqxwKBgQDPvcJkFqpPbxKNImyXtmVpoHIm9jWQtS6O\nQED7cyDF8ids8wOl2d/XqBybecufvxhsOybLmw8h5Dr7mT4LS+BlvL9du2fTzbIQ\n7NvYYqu7IxFjZgBtTFWefAf/WbAqwZQQmijYzP8px7MhouRPd8+K7HzSa+rAY2QC\neKvQWU2GewKBgQDZAzDUY20R6j+p7IiwRelfBonRCh7pPC3P5u+FnqcIRoKvQvxw\nMrR3phr1dBpVlCfc/w5xQPYd7Xhx68MMmC6clPRqbaIuqCyg8u9J3VAod1l+SQ4l\nAdvl5RJIYm5JHriMnJmAJtTSDPS7m+UtdJM47rmiKhwzN2IckjYrdKU9RQKBgD5u\nCXAou4/ZklqloLrLDpj6pbN9xEUzncUUHDM0uwGhryV3tn3uBu35UHeM15uvQvir\nohIIDDkkLHGV8OZWLB6G5X+WpTIqm7uoYr0ZkgBQHpaffbta+FQDdCfR3TZMLGH8\n4g+dM4VrxTJzkGctW0qlnTFjSw38EH8JoqCfZcPnAoGADJAuIw0O/BhNoZ2GAvoa\n7yhwgu3qyKcg6hjXvw1TyeoU3K60ujmX9IIgx2YrIV/sn6u72C7yHmASp9/vIY5P\nQzowcii4CO96+cDQ/a4Y17ikhcbV83bVMJVcziWJTIkhuhck6jVvWCCnBdw6ZuXU\n+N2y9wJc0Pt1065sQMqRiGc=\n-----END PRIVATE KEY-----\n"
    }
    
readiness_check:
  path: "/health"
  check_interval_sec: 5
  timeout_sec: 2
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300 # Adjust as needed
liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 5
  failure_threshold: 2
  success_threshold: 2